### ISSUE TITLE
Hidden fields dependent of css 

### ISSUE THREAD

**Issue by adelin-b** [isobar-us/redux-form-gen#27]
I was wondering why choosing to hide css with a class rather than not rendering the elements with conditional rendering ?

**Comment by bmv437** [comment]
Hey @adberard,

Using css `display: none;` to hide conditionally invisible fields was done in order to satisfy some advanced use-cases. It might be possible to move away from css and achieve the same result, but it would require a decent amount of refactor and testing. Let me give you more insight about one of these use-cases.

Specifically, fields that may be listening to changes to other fields values. For example, linking a dropdown with a numbers 0-10 to the length of a `FieldArray`. when the number is changed in the dropdown, push/pop values on the array to match the length. Same goes for the array. When items are removed/added, update the value of the dropdown to match. In order to react immediately to changes in values/length, the field components would need to be mounted.

This was done very early on in the design of the form generator, and my goal would be to make conditional visibility not depend on css `display:none` in the future, and just skip the render for hidden fields as you mentioned. I'll add this to my roadmap as something to explore.
